#!/usr/bin/python
import MySQLdb

db = MySQLdb.connect(host="localhost",    # your host, usually localhost
                     user="mehrab",         # your username
                     passwd="password",  # your password
                     db="python-db")        # name of the data base

# you must create a Cursor object. It will let
#  you execute all the queries you need
cur = db.cursor()

# Use all the SQL you like
cur.execute("SELECT * FROM auth_user")

# print all the first cell of all the rows
for row in cur.fetchall():
    print row[1]
    print row[3]

db.close()
